### ISSUE TITLE
Add Dark / White Mode to Portfolio (15. Simple Portfolio)

### ISSUE THREAD

**Issue by GouthamV10** [GouthamV10/30-JavaScript#4]
(go to 15. simple portfolio folder for project files)
Dark mode to my portfolio website to enhance user experience. Currently, the portfolio is built using HTML, CSS. The dark mode should be toggleable, and the user's preference should persist across page reloads.

Tasks

- Implement a button or toggle for switching between light and dark modes.
- Create CSS styles for both light and dark modes.
- Use JavaScript to handle the mode toggling and persist user preference.
- Test the implementation to ensure it works smoothly across different browsers.

**Comment by cjstyles6** [comment]
@GouthamV10 assign me to this issue

**Comment by GouthamV10** [comment]
@cjstyles6 assigned

**Comment by cjstyles6** [comment]
Done
